title: Veer Patta Public School
description: Bilingual learning environment nurturing leaders of tomorrow.
url: "https://veerpatta.github.io"
baseurl: "/veerpatta-website"
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
lang: en
permalink: pretty
collections:
  pages:
    output: true
  news:
    output: true
    permalink: /:collection/:name/

# School Contact & Location
school_name: "Veer Patta Public School"
school_phone: "+919413748575"
school_email: "veerpatta.school@gmail.com"
school_address: "Opp. Mela Ground, Amet, Rajasthan - 313332"
school_maps_url: "https://maps.google.com/?q=Veer+Patta+Public+School+Amet+Rajasthan"
school_geo_lat: "25.3040"
school_geo_lng: "73.9271"
school_hours: "Mo-Sa 08:00-14:00"
school_sameAs:
  - "https://www.facebook.com/veerpatta"
  - "https://www.youtube.com/@veerpatta"

# Analytics (privacy-safe, disabled by default)
analytics_enabled: false
analytics_script: "https://plausible.io/js/script.js"
analytics_domain: "veerpatta.github.io"
