title: Veer Patta Public School
description: Bilingual learning environment nurturing leaders of tomorrow.
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
lang: en
permalink: pretty
collections:
  pages:
    output: true
